(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=aa(this),m=function(a,b){if(b)a:{var c=l;a=a.split(".");for(var d=0;d<a.length-
1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&f(c,a,{configurable:!0,writable:!0,value:b})}};m("Symbol",function(a){if(a)return a;var b=function(g,h){this.g=g;f(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(g){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+d++,g)};return e});
var ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ca={a:!0},da={};try{da.__proto__=ca;p=da.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ea=n,q=function(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ea)ea(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.D=b.prototype};m("globalThis",function(a){return a||l});
m("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});var r=this||self,t=function(a){return a};var fa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var ha={},u=null;var ia="function"===typeof Uint8Array;var v="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function w(a){Object.isFrozen(a)||(v?a[v]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function ja(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var x,A=Object.freeze(w([])),ka="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;var B=function(a,b,c,d){b<a.i&&(void 0===d||!d)?a.g[b+a.h]=c:(a.j||(a.j=a.g[a.i+a.h]={}))[b]=c;return a};function la(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&ia&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!u){u={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));ha[e]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===u[k]&&(u[k]=h)}}}b=ha[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=
3){var y=a[g],z=a[g+1];k=a[g+2];h=b[y>>2];y=b[(y&3)<<4|z>>4];z=b[(z&15)<<2|k>>6];k=b[k&63];c[e++]=h+y+z+k}h=0;k=d;switch(a.length-g){case 2:h=a[g+1],k=b[(h&15)<<2]||d;case 1:a=a[g],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}return c.join("")}}return a};function ma(a,b){if(null!=a){if(Array.isArray(a))a=C(a,b);else if(ja(a)){var c={},d;for(d in a)c[d]=ma(a[d],b);a=c}else a=b(a);return a}}function C(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=ma(c[d],b);if(b=Array.isArray(a)){var e;v?e=a[v]:e=a.g;b=(null==e?0:e)&1}b&&w(c);return c}function na(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=la(a);return Array.isArray(a)?C(a,na):a};var oa;var D=function(a,b,c){var d=oa;oa=null;a||(a=d);d=this.constructor.C;a||(a=d?[d]:[]);this.h=(d?0:-1)-(this.constructor.B||0);this.l=void 0;this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],ja(d))){this.i=a-this.h;this.j=d;break a}void 0!==b&&-1<b?(this.i=Math.max(b,a+1-this.h),this.j=void 0):this.i=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.i)a+=this.h,(d=this.g[a])?Array.isArray(d)&&w(d):this.g[a]=A;else{d=this.j||(this.j=this.g[this.i+this.h]={});var e=d[a];e?Array.isArray(e)&&
w(e):d[a]=A}};D.prototype.toJSON=function(){var a=this.g;return x?a:C(a,na)};D.prototype.toString=function(){return this.g.toString()};function pa(a,b){return la(b)};var E=function(){D.apply(this,arguments)};q(E,D);var qa=function(){var a={};Object.defineProperties(E,(a[Symbol.hasInstance]={value:Object[Symbol.hasInstance],configurable:!1,writable:!1,enumerable:!1},a))};ka&&qa();var F=function(){E.apply(this,arguments)};q(F,E);var ra=function(){var a={};Object.defineProperties(F,(a[Symbol.hasInstance]={value:Object[Symbol.hasInstance],configurable:!1,writable:!1,enumerable:!1},a))};ka&&ra();var G,sa=function(){if(void 0===G){var a=null,b=r.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:t,createScript:t,createScriptURL:t})}catch(c){r.console&&r.console.error(c.message)}G=a}else G=a}return G};var H=function(a,b){this.g=b===ta?a:""};H.prototype.toString=function(){return this.g+""};var ta={};var ua={},I=function(a,b,c){this.g=c===ua?a:""};I.prototype.toString=function(){return this.g.toString()};/*

 SPDX-License-Identifier: Apache-2.0
*/
var xa=function(a,b){if(!va()){var c=Math.random();if(c<b)return c=wa(),a[Math.floor(c*a.length)]}return null},wa=function(){if(!globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},va=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return fa(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],ya)||1E-4>Math.random()}),ya=function(a){var b;
a:{if(b=r.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};var Aa=function(a){F.call(this,a,-1,za)};q(Aa,F);var Ba=function(a,b){return B(a,2,b)},Ca=function(a,b){return B(a,3,b)},Da=function(a,b){return B(a,4,b)},Ea=function(a,b){return B(a,5,b)},Fa=function(a,b){return B(a,9,b)},Ga=function(a,b){var c=void 0===c?!1:c;if(b){var d=w([]);for(var e=0;e<b.length;e++)d[e]=b[e].g;a.l||(a.l={});a.l[10]=b}else a.l&&(a.l[10]=void 0),d=A;return B(a,10,d,c)},Ha=function(a,b){return B(a,1,b)},Ia=function(a){F.call(this,a)};q(Ia,F);var za=[10,6];var Ja="platform platformVersion architecture model uaFullVersion bitness fullVersionList".split(" ");
function Ka(){var a,b;return"function"!==typeof(null===(b=null===(a=null===r||void 0===r?void 0:r.navigator)||void 0===a?void 0:a.userAgentData)||void 0===b?void 0:b.getHighEntropyValues)?null:r.navigator.userAgentData.getHighEntropyValues(Ja).then(function(c){var d;return Ga(Fa(Ea(Da(Ca(Ba(Ha(new Aa,c.platform),c.platformVersion),c.architecture),c.model),c.uaFullVersion),c.bitness),null===(d=c.fullVersionList)||void 0===d?void 0:d.map(function(e){var g=new Ia;g=B(g,1,e.brand);return B(g,2,e.version)}))})}
;var La=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(d){}return!0}(r,!1)?"https:":"http:",Ma={},Na=(Ma[1]="A4/Htern2udN9w3yJK9QgWQxQFruxOXsXL7cW60DyCl0EZFGCSme/J33Q/WzF7bBkVvhEWDlcBiUyZaim5CpFQwAAACceyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQ29udmVyc2lvbk1lYXN1cmVtZW50IiwiZXhwaXJ5IjoxNjQzMTU1MTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlLCJ1c2FnZSI6InN1YnNldCJ9",
Ma);var Oa={A:1,s:4,u:5,v:12},J={o:"40004006",m:"40004007"};function Pa(){return{1:.5,4:.02,5:.001,12:.001}}function Qa(){var a=Ra,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in Oa)if(b=a[Oa[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Sa(){var a=r.dcmads;if(null!=a.eids)return a.eids;var b=r.navigator;return b.connection&&b.connection.saveData?(a=xa([J.o,J.m],a.expts[4]))?"4|"+a:"":""}function Ta(){if(!r.dcmads.uach){var a=Ka();a&&a.then(function(b){var c=r.dcmads;a:{x=!0;try{var d=JSON.stringify(b.toJSON(),pa);break a}finally{x=!1}d=void 0}c.uach=d})}};try{r.dcmads=r.dcmads||{};r.dcmads.startTime=(new Date).getTime();var Ua=r.dcmads,K=r.dcmads.version,L={loader:245};if(K)if(L.experiment=K.experiment,84==K.number||"p"==K.number)L.number=84;else if(84==K.number||"c"==K.number)L.number=84;if(!L.number){var Va=xa([84,84],0);L.experiment=!!Va;L.number=Va||84}Ua.version=L;var Wa=r.dcmads,Xa,Ra=r.dcmads.expts,M;M=void 0===M?Pa:M;Xa=Qa()?Ra:M();Wa.expts=Xa;r.dcmads.eids=Sa();r.dcmads.ots=Na;Ta();var Ya="4|"+J.m,Za=r.dcmads.version,$a=Za.number,ab="";Za.experiment&&
84==$a&&(ab="?rxp=84x84");var bb="impl_v"+$a+".js"+ab,cb=r.document,db=cb.currentScript||Array.from(cb.getElementsByTagName("script")).pop(),N=(0==(db&&db.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+bb;if(r.dcmads.eids===Ya){var eb=r.document,O,fb=sa(),gb=fb?fb.createScriptURL(N):N;O=new H(gb,ta);var P,Q=eb;Q=void 0===Q?document:Q;P=Q.createElement("script");P.src=O instanceof H&&O.constructor===H?O.g:"type_error:TrustedResourceUrl";var hb,R,ib=(P.ownerDocument&&
P.ownerDocument.defaultView||window).document,S=null===(R=ib.querySelector)||void 0===R?void 0:R.call(ib,"script[nonce]");(hb=S?S.nonce||S.getAttribute("nonce")||"":"")&&P.setAttribute("nonce",hb);var T=eb.getElementsByTagName("script")[0];T&&T.parentNode&&T.parentNode.insertBefore(P,T)}else{var jb=r.document,U,kb='<script src="'+N+'">\x3c/script>',lb=sa(),mb=lb?lb.createHTML(kb):kb;U=new I(mb,null,ua);jb.write(U instanceof I&&U.constructor===I?U.g:"type_error:SafeHtml")}}catch(a){if(.01>Math.random()){var V=
"";try{var W,X=a.toString();a.name&&-1==X.indexOf(a.name)&&(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&(X+=": "+a.message);if(a.stack){var Y=a.stack,Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var nb;Y!=nb;)nb=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var ob=r.dcmads.eids,pb=document.createElement("img");pb.src=La+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=245&context=554"+
((ob?"&eids="+ob:"")+"&msg="+V);(r.google_image_requests=r.google_image_requests||[]).push(pb)}};}).call(this);
